apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 1Gi # Dung lượng PV (khớp với size trong values.yaml)
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: # Sử dụng hostPath cho môi trường như Docker Desktop
    path: /tmp/rabbitmq-data
