apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.default.svc.cluster.local:3100
      isDefault: true
      jsonData:
        maxLines: 1000
